//===-- WDC65816Subtarget.h - Define Subtarget for the WDC65816 -*- C++ -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the WDC65816 specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_WDC65816_SUBTARGET_H
#define LLVM_WDC65816_SUBTARGET_H

#include "llvm/Target/TargetSubtargetInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/CodeGen/SelectionDAGTargetInfo.h"

#include "WDC65816FrameLowering.h"
#include "WDC65816ISelLowering.h"
#include "WDC65816InstrInfo.h"

#define GET_SUBTARGETINFO_HEADER
#include "WDC65816GenSubtargetInfo.inc"

namespace llvm {

    /// A specific WDC65816 target.
    class WDC65816Subtarget : public WDC65816GenSubtargetInfo {
    public:
        //! Creates an WDC65816 subtarget.
        //! \param TT  The target triple.
        //! \param CPU The CPU to target.
        //! \param FS  The feature string.
        //! \param TM  The target machine.
        WDC65816Subtarget(const Triple &TT, const std::string &CPU, const std::string &FS,
                          WDC65816TargetMachine &TM);

        const WDC65816InstrInfo *getInstrInfo() const override { return &InstrInfo; }
        const TargetFrameLowering *getFrameLowering() const override { return &FrameLowering; }
        const WDC65816TargetLowering *getTargetLowering() const override { return &TLInfo; }
        const SelectionDAGTargetInfo *getSelectionDAGInfo() const override { return &TSInfo; }
        const WDC65816RegisterInfo *getRegisterInfo() const override { return &InstrInfo.getRegisterInfo(); }

        /// Parses a subtarget feature string, setting appropriate options.
        /// \note Definition of function is auto generated by `tblgen`.
        void ParseSubtargetFeatures(StringRef CPU, StringRef FS);

    private:
        WDC65816InstrInfo InstrInfo;
        WDC65816FrameLowering FrameLowering;
        WDC65816TargetLowering TLInfo;
        SelectionDAGTargetInfo TSInfo;
    };

} // end namespace llvm

#endif // LLVM_WDC65816_SUBTARGET_H
